version: "3"
services:
  node:
    build:
      context: ./docker
      dockerfile: Dockerfile_node
    stdin_open: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
